name: Deploy to ECR

on:
  pull_request:
    types: [closed]
    branches:
      - "main"
      - "release/**"
      - "dev/**"
  workflow_dispatch:

jobs:
  update_images:
    name: Build image
    runs-on: ubuntu-latest
    environment: Product
    permissions:
      id-token: write
      contents: write
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::012827087112:role/vfoody-github-actions 
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR Private
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: vfoody 
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:latest .
          docker push $REGISTRY/$REPOSITORY:latest

  run_ansible_backend:
    needs: update_images
    environment: Product
    name: update-docker-container
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    defaults:
      run:
        working-directory: ./ansible/
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: "Create env file"
        run: |
          echo "${{ secrets.INVENTORY }}" > ./inventory
          echo "${{ secrets.PEM }}" > ./vfoody.pem
          echo "${{ secrets.ENV }}" > ./env
          echo '${{ secrets.GOOGLE_SERVICE_JSON }}' > ./firebase_credentials.json          
      - name: "Create env file"
        run: |
          sudo chmod 400 ./vfoody.pem

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: docker.yaml
          directory: ./ansible/
          options: |
            --inventory inventory
